### ISSUE TITLE
V language - join efforts with py2v

### ISSUE THREAD

**Issue by dumblob** [py2many/py2many#319]
py2many looks like an interesting endeavour (I've just discovered it through https://news.ycombinator.com/item?id=27165366 ).

I wonder whether there would be some benefits from sharing some knowledge, experience, abstractions, code, templates, etc. with https://github.com/vlang/py2v .

**Comment by adsharma** [comment]
Looks interesting. I can see potential collaboration in a few areas:

* API plugins - translating the python stdlib to whatever V is using. py2many/py*/plugins.py (rust, cpp have it working. Other languages need more work)
* Some type of a pattern matching abstraction for python. Does V use match as a statement or an expression?
* Use of rewriters saved us from an explosion in complexity

I hope to make some documentation/video about the structure of py2many at some point. That could lead to a more in-depth discussion of these topics.

**Comment by dumblob** [comment]
@div72 @medvednikov thoughts?

**Comment by div72** [comment]
As of now, I don't think that py2many can benefit from py2v while py2v can benefit from py2many. Even if py2many had a V backend(which nsauzede has a simple PoC on their fork of py2many that I made some small improvements locally) since py2v is mostly written in V sharing work between them wouldn't be trivial.

That said I am planning on making a type analyzer which populates python ast with type annotations in the future. I believe that could be useful for all backends of py2many.

**Comment by adsharma** [comment]
Thank you for sharing your plans @div72. Does the type analyzer you're thinking about work differently from the one py2many has?

https://github.com/adsharma/py2many/blob/main/py2many/inference.py

Inferred types are stored in an attribute called "annotation" in the AST node.

**Comment by div72** [comment]
Yes, it'll also use annotation fields to store the types, although the implementation will differ.

**Comment by adsharma** [comment]
Are you planning to do a Hindley–Milner type inference or something else?

The current py2many implementation follows the rules of that type system, but has implementation holes such as:

```
def foo(a: List[T]) -> T: ..

x = foo([1, 2, 3])
```
We should infer the type of x to be int, but the code doesn't.

https://github.com/adsharma/py2many/issues/246 is also related.

**Comment by div72** [comment]
Planning on using abstract interpretation.

Seems like py2many's type inference also needs some work.

**Comment by adsharma** [comment]
> abstract interpretation

We use eval() to handle cases where someone does "import foo as bar". By using type classes instead of strings in our type maps, the translation is more robust.

https://github.com/adsharma/py2many/blob/main/py2many/clike.py#L95

> Seems like py2many's type inference also needs some work.

Other than the holes noted above? Would love to exchange ideas on where things can be improved.

**Comment by jayvdb** [comment]
Note py2many is py 3.8+ while py2v is 3.6+.

See https://github.com/adsharma/py2many/issues/96 for notes re inference tools.

For the ast->json step that py2v is currently doing, you might want to use https://github.com/YoloSwagTeam/ast2json - its tests pass on py36,8,9 , but it only has two (2) tests and there are issues raised which looks like they need fixing.

However it would be useful for py2many to be able to emit its enhanced ast as an intermediate format before it is passed to the per-language transpilers, and json seems like a reasonable choice, so we could add a cli option to do this, and then your json2v.v could ingest that.  We would want to add a py2many version into the json to assist with compatibility, as the py2many-enhanced-ast would be inherently unstable for quite a while.

Another possible (but more complicated) way to join efforts with py2many is for py2many to generate py2v.  i.e. create a py2many target language V (using a lot of the algorithms already in https://github.com/vlang/py2v/blob/master/json2v/json2v.v) and then use py2many to transpile py2many into V, but of course many more would be needed.
We already have tests which are doing this transpilation for each target language in https://github.com/adsharma/py2many/blob/main/tests/test_transpile_self.py , however they are all incomplete because py2many uses a lot of Python language features not yet supported by each of the transpilers, including stdlib and Python runtime features that we probably dont want to support in py2many.  However I believe it would be appropriate to be rewriting those chunks of py2many-code into py2many-compliant Python so that we can generate a transpiler for each language, written in code generated for that language.  The rust & cpp transpilers are furthermost down that path, and I am quite keen to get the rust one working.

**Comment by jayvdb** [comment]
I see https://github.com/adsharma/py2many/compare/main...nsauzede:f-v is the branch of the effort to create a V transpiler.

With #350 merged, there is now an intermediate format "Python" which includes most of the type inference, but notably excludes any comments from the input python (c.f. https://github.com/adsharma/py2many/issues/354 for comments support).  I think this is a better intermediate format than json, and we could embed hints in the generated Python as comments if we need to store additional metadata for other tools to use, that cant be represented in Python code.

**Comment by jayvdb** [comment]
@nsauzede , the `f-v-tryrebase` branch is looking pretty good.

`pyv/transpiler.py` needs to be run through `black` before a PR.

I recommend that the language "key" in `_get_all_settings` is changed from "v" to "vlang", and use `args.vlang` in `main`.  You'll see why soon.

Then we need some CI.  Ideally add one of the [Vlang github actions](https://github.com/search?q=vlang+github+action&type=source) to https://github.com/adsharma/py2many/blob/main/.github/workflows/main.yml

Then add a `vlang` entry to `COMPILERS` in https://github.com/adsharma/py2many/blob/main/tests/test_cli.py#L32 if applicable, and/or `INVOKER` directly below that.

Then run `UPDATE_EXPECTED=1 KEEP_GENERATED=1 tox -e py39 -- -k 'CLI and vlang'`.  This will attempt to generate  vlang code for each of the test cases in https://github.com/adsharma/py2many/tree/main/tests/cases , and put the generated code into `tests/build`, and if they pass the test the code will be put into `tests/expected`.

Iterate to improve the transpiler to fix any problems found, but you dont need to get all of the test cases working.

Add any passing tests in `tests/expected` to git.  Only these cases which are checked in will be tested in CI.

Also run `tox -e py39 -- -k 'unsupported and vlang'`.  If any of these "unsupported" snippets actually work with the vlang transpiler, you can add them to `EXPECTED_SUCCESSES` in https://github.com/adsharma/py2many/blob/main/tests/test_unsupported.py

If your transpiler is fairly advanced, you could also add a test method in https://github.com/adsharma/py2many/blob/main/tests/test_transpile_self.py , e.g. copying `test_dart_recursive`.  If the transpiler is raising exceptions, you can mask them using `_suppress_exceptions=(TypeError, IndexError, Etc)`.

**Comment by nsauzede** [comment]
- fixed the key to vlang
- ran `black`

**Comment by jayvdb** [comment]
Done! ;-)
