### ISSUE TITLE
tests/cases/comparison.dart:7:7: Error: 's' is already declared in this scope. Looks like it need to check if a variable is define in the outer-scope already

### ISSUE THREAD

**Issue by mw66** [py2many/py2many#604]
$ py2many --dart=1 tests/cases/comparison.py

```
tests/cases/comparison.dart:7:7: Error: 's' is already declared in this scope.
  var s;
      ^
tests/cases/comparison.dart:6:7: Context: Previous declaration of 's'.
  int s = 1;
      ^
```

Looks like it need to check if a variable is define in the outer-scope already

```
$ cat tests/cases/comparison.dart
// @dart=2.9
import 'package:sprintf/sprintf.dart';

compare_with_integer_variable() {
  int i = 0;
  int s = 1;
  var s;

  if (i) {
    var s = 2;
  } else {
    var s = 3;
  }
  assert(s == 3);
}

use_zero_for_comparison() {
  int i = 0;
  int s = 1;
  var s;

  if (0) {
    var s = 2;
  } else {
    var s = 3;
  }
  assert(s == 3);
}

main(List<String> argv) {
  compare_with_integer_variable();
  use_zero_for_comparison();
  print(sprintf("%s", ["OK"]));
}

```

**Comment by adsharma** [comment]
Some of these errors are highly specific to the version of $lang being used.
We used to catch them using CI/CD (fast.yaml). But it's expensive to run because of the large matrix of os * python-version * language-version mix.

So I recently disabled it. But we can run it one language at a time. Let me kick off a dart-lang run to see if it passes.

**Comment by mw66** [comment]
I discovered this bug, because my dlang transpiler is based on Dart's. And my dlang fix for the issue is here:

https://github.com/mw66/py2many/blob/2b39378b493dcba969079cfaa3976ecfeac9c9e2/pyd/transpiler.py#L529
